spring:
  datasource:
    username: postgres
    password: 5502
    driverClassName: org.postgresql.Driver
    driverDialect: org.hibernate.dialect.PostgreSQL82Dialect
    url: jdbc:postgresql://localhost/lab3db
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: 8087

logging:
  level:
    root: DEBUG